name: datavault_vs_star

profile: datavault_vs_star

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  datavault_vs_star:
    +static_analysis: strict
    staging:
      +materialized: view
    data_vault:
      hubs:
        +materialized: incremental
      links:
        +materialized: incremental
      satellites:
        +materialized: incremental
